server:
  port: 8080
#  ssl:
#    key-store: classpath:ssl/keystore.p12
#    key-store-type: PKCS12
#    key-store-password: cjswo1!


django:
  endpoint:
    gpu-server-1: 192.168.0.14:7070
    gpu-server-2: 70.12.130.121:17070
  protocol: http

app:
  savedimage:
    rootpath:
